FROM node:20-alpine

WORKDIR /app

# ✅ ADD CURL FOR HEALTHCHECK (apk for Alpine)
RUN apk add --no-cache curl

# 1) package files
COPY package*.json ./

# 2) prisma schema pehle copy karo (postinstall ko schema mil jayega)
COPY prisma ./prisma

# 3) ab install (postinstall: prisma generate yahin chalega)
RUN npm install

# 4) baaki code
COPY . .

EXPOSE 3000
